"""Rebuild Full-App Glass's original, tintable line icons. Build has no Python dependency."""
import base64
import io
import json
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
S = 16

def icon(name):
    image = Image.new('RGBA', (24*S, 24*S))
    draw = ImageDraw.Draw(image)
    def line(points, width=1.6):
        points = [(int(x*S), int(y*S)) for x, y in points]
        draw.line(points, fill='white', width=round(width*S), joint='curve')
        r = width*S/2
        for x, y in (points[0], points[-1]):
            draw.ellipse((x-r,y-r,x+r,y+r),fill='white')
    def ellipse(box, width=1.6):
        draw.ellipse(tuple(round(x*S) for x in box),outline='white',width=round(width*S))
    def rounded(box, radius=3):
        draw.rounded_rectangle(tuple(round(x*S) for x in box),radius=round(radius*S),outline='white',width=round(1.6*S))
    if name == 'ChatIcon':
        rounded((3,4,21,18),4); line([(8,18),(5,21),(5,16)])
    elif name == 'MagnifyingGlassIcon':
        ellipse((3,3,17,17)); line([(16,16),(21,21)])
    elif name == 'HomeIcon':
        line([(2.5,10),(12,3),(21.5,10)]); line([(5,9),(5,21),(10,21),(10,14),(14,14),(14,21),(19,21),(19,9)])
    elif name == 'BellIcon':
        line([(4,17),(6,14),(6,9),(7,6),(10,4),(14,4),(17,6),(18,9),(18,14),(20,17),(4,17)])
        draw.arc((9*S,17*S,15*S,22*S),0,180,fill='white',width=round(1.6*S))
    elif name == 'ImageIcon':
        rounded((3,3,21,21)); ellipse((6.5,6.5,10.5,10.5)); line([(4,18),(10,12),(14,16),(17,13),(21,17)])
    elif name == 'MusicIcon':
        line([(10,18),(10,5),(20,3),(20,16)]); ellipse((4,16,10,21)); ellipse((14,14,20,19))
    elif name == 'MicrophoneIcon':
        rounded((9,2.5,15,15),3); line([(6,11),(6,14),(8,18),(12,19),(16,18),(18,14),(18,11)]); line([(12,19),(12,22)]); line([(8,22),(16,22)])
    elif name == 'UserIcon':
        ellipse((8,3,16,11)); draw.arc((4*S,14*S,20*S,28*S),180,360,fill='white',width=round(1.6*S)); line([(4,21),(20,21)])
    elif name == 'SettingsIcon':
        line([(4,6),(8,6)]);line([(13,6),(20,6)]);ellipse((8,3.5,13,8.5))
        line([(4,12),(14,12)]);line([(19,12),(20,12)]);ellipse((14,9.5,19,14.5))
        line([(4,18),(6,18)]);line([(11,18),(20,18)]);ellipse((6,15.5,11,20.5))
    image = image.resize((96,96),Image.Resampling.LANCZOS)
    stream = io.BytesIO();image.save(stream,format='PNG',optimize=True)
    return 'data:image/png;base64,'+base64.b64encode(stream.getvalue()).decode()

names=['ChatIcon','MagnifyingGlassIcon','HomeIcon','BellIcon','ImageIcon','MusicIcon','MicrophoneIcon','UserIcon','SettingsIcon']
target=ROOT/'plugins/com.cuddled.fullappglass/js/lineIcons.ts'
target.write_text('// Generated by scripts/generate-full-app-icons.py.\nexport default '+json.dumps({name:icon(name) for name in names},indent='\t')+' as const\n')
